Update Makefile

diff --git a/trunk/user/frp/Makefile b/trunk/user/frp/Makefile
--- a/trunk/user/frp/Makefile
+++ b/trunk/user/frp/Makefile
@@ -1,37 +1,20 @@
 THISDIR := $(shell pwd)
-FRP_VER := 0.50.0
-FRP_URL_BASE := https://github.com/fatedier/frp/releases/download
-FRP_NAME := frp_$(FRP_VER)_linux_mipsle
-FRP_URL := $(FRP_URL_BASE)/v$(FRP_VER)/$(FRP_NAME).tar.gz
 
-all: download_test extra_test
+all: extra_test
 	@echo "frp build done!"
 
-download_test:
-	( if [ ! -f $(FRP_NAME).tar.gz ]; then \
-		wget -t5 --timeout=20 --no-check-certificate -O $(FRP_NAME).tar.gz $(FRP_URL); \
-	fi )
-
 extra_test:
-	( if [ ! -d $(FRP_NAME) ]; then \
-		mkdir -p $(FRP_NAME); \
-		if [ "$(CONFIG_FIRMWARE_INCLUDE_FRPC)" = "y" ]; then \
-			tar xf $(FRP_NAME).tar.gz $(FRP_NAME)/frpc $(FRP_NAME)/frpc.toml $(FRP_NAME)/LICENSE; \
-		fi; \
-		if [ "$(CONFIG_FIRMWARE_INCLUDE_FRPS)" = "y" ]; then \
-			tar xf $(FRP_NAME).tar.gz $(FRP_NAME)/frps $(FRP_NAME)/frps.toml $(FRP_NAME)/LICENSE; \
-		fi; \
+	( if [ ! -f frpc ]; then \
+		echo "Error: frpc not found in current directory"; \
+		exit 1; \
 	fi )
 
 clean:
-	#rm -rf $(FRP_NAME).tar.gz $(FRP_NAME)
+	#rm -rf frpc
 
 romfs:
 ifeq ($(CONFIG_FIRMWARE_INCLUDE_FRPC),y)
-	$(ROMFSINST) -p +x $(THISDIR)/$(FRP_NAME)/frpc /usr/bin/frpc
-endif
-ifeq ($(CONFIG_FIRMWARE_INCLUDE_FRPS),y)
-	$(ROMFSINST) -p +x $(THISDIR)/$(FRP_NAME)/frps /usr/bin/frps
+	$(ROMFSINST) -p +x $(THISDIR)/frpc /usr/bin/frpc
 endif
 	$(ROMFSINST) -p +x $(THISDIR)/frp.sh /usr/bin/frp.sh
 	$(ROMFSINST) /etc_ro/frp_script.sh
